# This is a basic workflow to help you get started with Actions

name: release

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab or through HTTP API
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  release:
    name: 'Release Data'
    runs-on: ubuntu-latest

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash

    steps:
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Checkout
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        submodules: true

    - name: Check Commit Message
      run: echo "COMMIT_MESSAGE=$(git log -1 --pretty=format:"%s")" >> $GITHUB_ENV

    - name: Build Script
      run: |
        npm ci
        npm run build

    - name: Run Script
      run: |
        npm run start
        tar -zcf release.tar.gz output

    - name: Add SHORT_SHA env property with commit short sha
      run: echo "SHORT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

    - name: Release Data
      id: create_release
      uses: ncipollo/release-action@v1
      with:
        name: ${{ env.COMMIT_MESSAGE }}
        artifacts: "release.tar.gz"
        token: ${{ secrets.GITHUB_TOKEN }}
        tag: ${{ env.SHORT_SHA }}